### ISSUE TITLE
The panos_software module doesn't work to a firewall through Panorama.

### ISSUE THREAD

**Issue by ntwrkguru** [PaloAltoNetworks/pan-os-ansible#301] opened 2022-03-03 21:35 UTC
## Describe the bug

The panos_software module doesn't work through Panorama. The error emitted is:
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'PanOSVersion' object has no attribute 'version'`

## Expected behavior

The docs claim it is supported in Panorama, so perhaps this is a doc issue not a bug per se.

## Current behavior

Error is emitted. Full ansible traceback:
```
task path: /Users/homer_simpson/Repos/panorama-scripts/ansible/roles/panos-download/tasks/main.yml:16
<x.x.x.x> ESTABLISH LOCAL CONNECTION FOR USER: homer_simpson
<x.x.x.x> EXEC /bin/sh -c 'echo ~homer_simpson && sleep 0'
<x.x.x.x> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/homer_simpson/.ansible/tmp `"&& mkdir "` echo /Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907 `" && echo ansible-tmp-1646343173.5811331-23108-241917439483907="` echo /Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907 `" ) && sleep 0'
Using module file /Users/homer_simpson/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py
<x.x.x.x> PUT /Users/homer_simpson/.ansible/tmp/ansible-local-23019vklc3y53/tmppfkmqcr7 TO /Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py
<x.x.x.x> EXEC /bin/sh -c 'chmod u+x /Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/ /Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py && sleep 0'
<x.x.x.x> EXEC /bin/sh -c '/usr/local/bin/python3 /Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py && sleep 0'
<x.x.x.x> EXEC /bin/sh -c 'rm -f -r /Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py", line 100, in <module>
    _ansiballz_main()
  File "/Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', _modlib_path=modlib_path),
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/92/z1f1fhjs01q90ddpjzfxlyy14bw5r5/T/ansible_paloaltonetworks.panos.panos_software_payload_otp0pbaz/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py", line 222, in <module>
  File "/var/folders/92/z1f1fhjs01q90ddpjzfxlyy14bw5r5/T/ansible_paloaltonetworks.panos.panos_software_payload_otp0pbaz/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py", line 181, in main
  File "/Users/homer_simpson/Library/Python/3.9/lib/python/site-packages/panos/__init__.py", line 222, in __ne__
    return not self.__eq__(other)
  File "/Users/homer_simpson/Library/Python/3.9/lib/python/site-packages/panos/__init__.py", line 211, in __eq__
    if self.mainrelease != other.mainrelease:
  File "/Users/homer_simpson/Library/Python/3.9/lib/python/site-packages/panos/__init__.py", line 150, in mainrelease
    return self.version[0:3]
AttributeError: 'PanOSVersion' object has no attribute 'version'
fatal: [pair1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/homer_simpson/.ansible/tmp/ansible-tmp-1646343173.5811331-23108-241917439483907/AnsiballZ_panos_software.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', _modlib_path=modlib_path),\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/92/z1f1fhjs01q90ddpjzfxlyy14bw5r5/T/ansible_paloaltonetworks.panos.panos_software_payload_otp0pbaz/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py\", line 222, in <module>\n  File \"/var/folders/92/z1f1fhjs01q90ddpjzfxlyy14bw5r5/T/ansible_paloaltonetworks.panos.panos_software_payload_otp0pbaz/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py\", line 181, in main\n  File \"/Users/homer_simpson/Library/Python/3.9/lib/python/site-packages/panos/__init__.py\", line 222, in __ne__\n    return not self.__eq__(other)\n  File \"/Users/homer_simpson/Library/Python/3.9/lib/python/site-packages/panos/__init__.py\", line 211, in __eq__\n    if self.mainrelease != other.mainrelease:\n  File \"/Users/homer_simpson/Library/Python/3.9/lib/python/site-packages/panos/__init__.py\", line 150, in mainrelease\n    return self.version[0:3]\nAttributeError: 'PanOSVersion' object has no attribute 'version'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

## Steps to reproduce

Run this task against a firewall that is managed by Panorama. The provider block has the Panorama IP and credentials along with the device serial number.

- name: Downloading base PAN-OS {{ base_version }}, if needed
  connection: local
  paloaltonetworks.panos.panos_software:
    provider: "{{ primary }}"
    version: "{{ base_version }}"
    sync_to_peer: "{{ sync_panos_to_peer | default(true)}}"
    install: "{{ install_panos | default(false) }}"
    restart: "{{ restart }}"

## Context

use case is to manage hundreds of firewalls via Ansible, but not need to create service accounts on every device. Instead, Panorama would be used as a consolidated access point.

## Your Environment

- Collection: 2.7.0
- Python: 3.9.6
- Ansible: 2.11.6
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2): pan-os-python 1.6.0

**Comment by jamesholland-uk** [comment] 2023-02-14 13:53
As discussed, I haven't been able to reproduce this issue, @ntwrkguru. Things may have moved on since this was opened, so we'll close it. We can always reopen later if needed.

**Closed by jamesholland-uk** 2023-02-14 13:53 UTC
Labels: bug

**Comment by appandya84** [comment] 2023-02-14 17:27
@jamesholland-uk @ntwrkguru Are we saying that panos_software module now supports software upgrade for firewall from Panorama? If yes please can you send guide or instructions for this? Thanks

**Comment by jamesholland-uk** [comment] 2023-02-14 17:51
@appandya84 I was using [this playbook](https://github.com/jamesholland-uk/playground/blob/main/pan-os-ansible/upgrade-mgd-devices.yml) to test the `panos_software` module. I was able to use each task individually to do download/install/reboot separately, plus the final task on its own to do all three in one task. This is using the module per the [documentation](https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_software_module.html). Let me know if this helps you

**Comment by appandya84** [comment] 2023-02-17 15:31
@jamesholland-uk Did you run this playbook on firewall itself for an upgrade? or did you run on panorama and let panorama connect to firewall for upload/install image etc? thanks

**Comment by jamesholland-uk** [comment] 2023-02-22 11:46
@appandya84 I used that playbook to target Panorama, passing in the value for the `serial_number` variable to specify which firewall needed upgrading

**Comment by appandya84** [comment] 2023-03-09 17:26
@jamesholland-uk Sorry for the late reply, I was away. Thanks for pointing this out. 
So will Panorama automatically downloads that version to Panorama first before it will push/upload/install it to firewall? or task will need to be written to have imaged downloaded on Panorama first? 
Also 'version' field will need just version number (for example 8.1.15) or actual file name (for example PanOS_vm-8.1.15) ?

**Comment by jamesholland-uk** [comment] 2023-03-10 10:03
The `panos_software` module today, when targeting Panorama and passing the serial number of a managed device, will use Panorama as a proxy to instruct the firewall to download the software itself from the Internet-hosted Palo Alto Networks update servers.

If you want to use Panorama to transfer the software to the managed device, and install it, you could look at [this example playbook](https://github.com/jamesholland-uk/playground/blob/main/pan-os-ansible/upgrade_offline_from_rama.yml), which has the transfer task I believe you are after.

**Comment by appandya84** [comment] 2023-03-10 17:09
@jamesholland-uk Yes panos_software in that case won't work in our environment as firewalls are offline and managed by Panorama. Second option I have already tested it good. thanks
