### ISSUE TITLE
paloaltonetworks.panos.panos_commit_push not pushing to devices in device group

### ISSUE THREAD

**Issue by richardjohnallsopp** [PaloAltoNetworks/pan-os-ansible#400] opened 2023-03-02 11:52 UTC
## Describe the bug

When using the `paloaltonetworks.panos.panos_commit_push` module the committed config in Panorama is not pushed to the devices in the specified device group. 

## Expected behaviour

I expected after using the `paloaltonetworks.panos.panos_commit_panorama` module to push changes to Panorama device groups that I would be able to use `paloaltonetworks.panos.panos_commit_push` module to push these changes to the devices in the specified device group.

## Current behavior

The `paloaltonetworks.panos.panos_commit_panorama` seems to work and I see the changes committed to Panorama for the specified device group, but after the `paloaltonetworks.panos.panos_commit_push` task completes successfully Panorama tells me that a push is needed as there is outstanding changes that were not pushed to devices. We have to manually push these changes. 

## Steps to reproduce

1. Using the latest collection version you should be able to push a commit to a Panorama device group and then use the push module to push the changes to the devices.

## Screenshots

![image](https://user-images.githubusercontent.com/50882889/222419726-645e0699-1f0f-432b-af57-c0ac5610352d.png)
![image](https://user-images.githubusercontent.com/50882889/222419886-16931b89-aaca-4359-9787-b2e08b517d46.png)

## Context

I've written a pipeline for automating the creation of objects, services and policies so we can convert this workflow into a Jenkins pipeline and IaC. It all works fine aside from the commit push meaning we cannot use the pipeline in production.

```
    - name: Create object(s) in Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        address_type: '{{ item.type }}'
        description: '{{ item.description }}'
        tag: '{{ item.tag | default(omit) }}'
        device_group: '{{ item.device_group }}'
        state: '{{ item.state }}'
      with_items: '{{ world_object }}'
      when: world_object is defined and item.state == 'present'

    - name: Create global service(s) in Panorama
      paloaltonetworks.panos.panos_service_object:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        destination_port: '{{ item.destination_port }}'
        source_port: '{{ item.source_port | default(omit) }}'
        protocol: '{{ item.protocol }}'
        description: '{{ item.description }}'
        tag: '{{ item.tag | default(omit) }}'
        device_group: '{{ item.device_group }}'
        state: '{{ item.state }}'
      with_items: '{{ world_service }}'
      when: world_service is defined and item.state == 'present'

    - name: Manage post-rule(s) in Panorama
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ provider }}'
        rule_name: '{{ item.name }}'
        rulebase: 'post-rulebase'
        location: '{{ item.location }}'
        existing_rule: '{{ item.existing_rule }}'
        description: '{{ item.description }}'
        source_zone: '{{ item.source_zone }}'
        destination_zone: '{{ item.destination_zone }}'
        source_ip: '{{ item.source_ip }}'
        source_user: '{{ item.source_user }}'
        destination_ip: '{{ item.destination_ip }}'
        category: '{{ item.category }}'
        application: '{{ item.application }}'
        service: '{{ item.service }}'
        hip_profiles: '{{ item.hip_profiles | default(omit) }}'
        action: '{{ item.action }}'
        device_group: '{{ item.device_group }}'
        disabled: '{{ item.disabled }}'
        state: '{{ item.state }}'
        # commit: '{{ item.commit }}'
      with_items: '{{ world_policy }}'

    - name: Remove object(s) in Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        address_type: '{{ item.type }}'
        description: '{{ item.description }}'
        tag: '{{ item.tag | default(omit) }}'
        device_group: '{{ item.device_group }}'
        state: '{{ item.state }}'
      with_items: '{{ world_object }}'
      when: world_object is defined and item.state == 'absent'

    - name: Remove global service(s) in Panorama
      paloaltonetworks.panos.panos_service_object:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        destination_port: '{{ item.destination_port }}'
        source_port: '{{ item.source_port | default(omit) }}'
        protocol: '{{ item.protocol }}'
        description: '{{ item.description }}'
        tag: '{{ item.tag | default(omit) }}'
        device_group: '{{ item.device_group }}'
        state: '{{ item.state }}'
      with_items: '{{ world_service }}'
      when: world_service is defined and item.state == 'absent'

    # spacific panorama commit
    - name: Commit candidate config on Panorama
      paloaltonetworks.panos.panos_commit_panorama:
        provider: '{{ provider }}'
        device_groups:
          - 'World'
        admins:
          - 'admin'
        description: 'Commit - {{ commit_description }}'
        sync: true
      tags:
        - "push"

    - name: Commit and push config via Panorama
      paloaltonetworks.panos.panos_commit_push:
        provider: '{{ provider }}'
        style: 'device group'
        name: 'World'
        #admins:
        #  - 'admin'
        sync: true
        description: 'Push - {{ commit_description }}'
      tags:
        - "push"
```

## Your Environment

- Collection: 2.13.2
- Python: 3.9.11
- Ansible: 2.10.6
- PAN-OS Python Library & version pan-os-python==1.8.1, pandevice==0.14.0
- Panorama: 10.2.3-h4

**Comment by jamesholland-uk** [comment] 2023-03-03 17:24
Hi @richardjohnallsopp, does the config definitely not push to the managed devices (NGFWs) with your playbook?
With Panorama 10.2.3-h4 I can replicate the GUI issue, where all managed devices are in sync but the GUI still incorrectly shows the icon and tooltip stating "pending push changes". This is a PAN-OS issue which needs to be reported through your usual support channel. However, I used the tasks in the example playbook above, and whilst that GUI issue is present, the playbook did actually push and commit the changes to the managed devices successfully, so I was unable to replicate an issue with the Ansible modules. Please let us know, thanks

**Comment by richardjohnallsopp** [comment] 2023-03-04 07:56
Hey @jamesholland-uk, I can confirm that the changes are not pushed to the firewalls, I'd be interested in seeing if your task in Panorama for the push shows devices it pushed to. Mine as above is empty and completes much faster than a manual push to that device group from Panorama.

Panorama also shows that all devices in the device group are out of sync after the Ansible push completes which currently blocks any future changes by other users.

**Comment by jamesholland-uk** [comment] 2023-03-06 10:36
Hi @richardjohnallsopp, yes, mine did have the managed device listed and took a "usual" duration to complete the push:
![Screenshot 2023-03-06 at 10 22 25](https://user-images.githubusercontent.com/6574404/223083804-f68181ee-ffb7-409e-b020-88c090fb044d.png)

And the managed device is in sync after:
![Screenshot 2023-03-06 at 10 33 26](https://user-images.githubusercontent.com/6574404/223085849-b301a6ff-f7c6-4e80-8def-43fcf710d1a7.png)


If the push to the managed devices(s) does not really happen, you can understand it not being in sync. The question therefore is, why is the push is not initiating properly?

For reference, here's the simplified version of the playbook I am using:
```
---
- name: Palo Alto Playbook
  hosts: '{{ target | default("host_homelabrama") }}'
  connection: local

  vars:
    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"
    commit_description: "Change ref 123"

  tasks:
    - name: Create object(s) in Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        name: 'aaaa-ertert'
        value: '1.1.1.1'
        device_group: 'poc-dg'

    # spacific panorama commit
    - name: Commit candidate config on Panorama
      paloaltonetworks.panos.panos_commit_panorama:
        provider: '{{ provider }}'
        device_groups:
          - 'poc-dg'
        admins:
          - 'ansible-admin'
        description: 'Commit - {{ commit_description }}'
        sync: true
      tags:
        - "push"

    - name: Commit and push config via Panorama
      paloaltonetworks.panos.panos_commit_push:
        provider: '{{ provider }}'
        style: 'device group'
        name: 'poc-dg'
        # admins:
        #   - 'admin'
        sync: true
        description: 'Push - {{ commit_description }}'
      tags:
        - "push"
```

**Comment by richardjohnallsopp** [comment] 2023-03-06 11:19
Yeah that does not happen with mine. Our plays are virtually the same as well, but my commit task is blank. 

Are we running the same versions of the collections and Ansible etc...

**Comment by jamesholland-uk** [comment] 2023-03-06 13:08
I'm on ansible-core 2.14.3, PAN-OS collection 2.13.2, python 3.10.9, pan-os-python 1.8.1

**Comment by jamesholland-uk** [comment] 2023-03-06 13:09
There's nothing in the `device_groups` or `admins` parameters that would lead to an empty commit or push is there? No unintended values for those parameters? Mine are all hard-coded, your config tasks use a variable on the device_groups for example?

**Comment by richardjohnallsopp** [comment] 2023-03-06 14:06
Not that I can see, I used the same variables to commit the code to Panorama and that looks solid, the push is just style: device group and name: World. I can try with latter versions and see if that makes a difference. Richard AllsoppEpic GamesSenior Infrastructure Engineer Mobile +447590263111On 6 Mar 2023, at 13:10, James Holland ***@***.***> wrote:﻿
There's nothing in the device_groups or admins parameters that would lead to an empty commit or push is there? No unintended values for those parameters? Mine are all hard-coded, your config tasks use a variable on the device_groups for example?

**Comment by scottgravitt** [comment] 2023-03-07 16:00
It looks like the config gets trucated: 
```
  <destination-h <<< here 
2023-03-03 15:24:49.112 +0000 Warning:  pan_hash_init(pan_hash.c:113): nbuckets 16536 is not power of 2!
2023-03-03 15:24:49.190 +0000 String is <entry name="ANSIBLE policy deployment test" uuid="67875cd0-9a6b-4785-9d3e-5c9ad12656d7">

and 

  <destination-hi <<< here
2023-03-03 15:24:49.212 +0000 pan_cfg_replaydb_get_uncommited_changes_mongo: Retrieved 100 uncommited replaydb entries from mongo db
2023-03-03 15:24:49.299 +0000 Error:  pan_cfg_get_session_by_cookie(pan_cfg_mgr.c:14810): session with cookie static doesn't exist
2023-03-03 15:24:49.299 +0000 Error:  pan_cfg_get_session_by_cookie(pan_cfg_mgr.c:14810): session with cookie static doesn't exist
2023-03-03 15:24:52.289 +0000 Error:  pan_job_refresh_job_cache(pan_job_mgr.c:13228): job 1320358 not found
```
[02485185_confd.txt](https://github.com/PaloAltoNetworks/pan-os-ansible/files/10911323/02485185_confd.txt)

We are also seeing configd crash, the root partition filling up and the HA Panorama pair failing over: 
```
/opt/panlogs/cores/:
total 0

/var/cores/:
total 8.0K
drwxr-xr-x 2 root root 4.0K Feb 28 06:20 crashinfo
drwxr-xr-x 2 root root 4.0K Mar 3 21:49 crashjobs <<<

/var/cores/crashinfo:
total 512K
rw-rw-rw 1 root root 507K Feb 28 06:20 reportd-20230228062014-10.2.3-h4.info

/var/cores/crashjobs:
total 0
rw-rr- 1 root root 0 Feb 23 19:28 configd-20230223192848.tmp
rw-rr- 1 root root 0 Mar 3 21:49 configd-20230303214911.tmp <<<
```
Panoramas failed over:
```
2023/03/03 21:50:30 2023/03/03 21:50:30 critical ha system- 0 000702890609 High root partition usage; going to state Non-Functional
2023/03/03 21:50:30 2023/03/03 21:50:30 critical ha state-c 0 000702890609 Moved from state Active to state Non-Functional
```
We have asked for verification on this defect being impacted in 10.2 code. At present the Panoramas are running 10.2.3-h4 but the firewalls are on 10.1.6-h6: PAN-160053 - Fixed an issue in Panorama where a process (configd) stopped responding due to a race condition in the mongodbprocess.

Palo Case: 02485185S2

**Comment by jamesholland-uk** [comment] 2023-03-08 09:09
Thanks @scottgravitt, is this the same deployment as @richardjohnallsopp or are you separate? We can leave this issue open for no if you want, or close it (knowing that you can reopen it if the TAC ticket does not fix the root cause and you want to circle back to the Ansible module)?

**Comment by scottgravitt** [comment] 2023-03-08 20:16
This is the same environment @jamesholland-uk. I am waiting for a meeting w/ TAC to 'rebuild the mongodb from root.' This should happen either later today or tomorrow, so let's leave it open and I'll update on the outcome.

**Comment by scottgravitt** [comment] 2023-03-25 01:43
@jamesholland-uk we are still working with PA TAC on a root cause here. It definitely seems to be an issue on our Panorama, so from my perspective we can close this one out and we'll provide an update on the root cause/workaround/fix as the information becomes available.

**Comment by jamesholland-uk** [comment] 2023-03-27 08:26
Thank you for the update @scottgravitt, much appreciated. I hope the issue gets resolved ASAP. If you do need to revisit the behaviour of this module, you can always reopen this Issue or create a new one.

**Comment by cdot65** [comment] 2023-06-02 19:06
I have been able to reproduce this situation in my lab environment,

```bash
❯ pip freeze | grep ansible
ansible==8.0.0
ansible-core==2.15.0

❯ pip freeze | grep pan-
pan-os-python==1.11.0
pan-python==0.17.0

❯ ansible-galaxy collection list | grep palo
paloaltonetworks.panos 2.16.0 
```

Panorama version `10.2.4`

```yaml
---
- hosts: panorama
  connection: local
  gather_facts: False
  become: False

  tasks:
    - name: "Creating a test address object"
      paloaltonetworks.panos.panos_address_object:
        provider:
          ip_address: "{{ ansible_host }}"
          api_key: "{{ panorama_api_key }}"
        name: "Gaming-PC"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "Gaming PC"
        device_group: "headquarters"
        state: "absent"
      register: result

    - name: commit candidate configs on panorama
      paloaltonetworks.panos.panos_commit_panorama:
        provider:
          ip_address: "{{ ansible_host }}"
          api_key: "{{ panorama_api_key }}"

    - name: push device group configs
      paloaltonetworks.panos.panos_commit_push:
        provider:
          ip_address: "{{ ansible_host }}"
          api_key: "{{ panorama_api_key }}"
        style: "device group"
        name: "headquarters"
        description: "This is a test."
```

result screenshot

<img width="817" alt="image" src="https://github.com/PaloAltoNetworks/pan-os-ansible/assets/76797306/714941a9-0554-447c-8c57-d092baa4722e">

Object is never pushed to remote firewalls in Device Group.

**Comment by jamesholland-uk** [comment] 2023-06-05 15:12
Happy to help if we can find a way to successfully reproduce this 👍

**Comment by richardjohnallsopp** [comment] 2023-06-06 14:00
@jamesholland-uk can we get this re-opened?

**Comment by cdot65** [comment] 2023-07-07 11:03
> Has anyone found a way to reproduce this issue yet? Thanks :)

Yes, I have reproduced this issue. I hope what I [provided here](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/400#issuecomment-1574188350) is sufficient

**Comment by jamesholland-uk** [comment] 2023-08-16 14:41
Sadly I can't replicate it still mate, @cdot65
I used pretty much everything the same as you?

Env:
![Screenshot 2023-08-16 at 15 33 32](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/ba493e7d-2026-417d-be5c-8773787983fe)

Playbook:
![Screenshot 2023-08-16 at 15 31 08](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/2e5a4bd4-1a76-427f-bc62-9aa9e47325f3)

Execution:
![Screenshot 2023-08-16 at 15 32 18](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/667fe25c-076d-4c35-b1fb-70604538fb68)
![Screenshot 2023-08-16 at 15 32 35](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/c8da1ba9-01c8-42b6-9465-c256b4f10a25)

Then I noticed your playbook was to delete that address object, and I did not have that object to delete, not a fair test. So I changed state to `present` and went again:

Playbook:
![Screenshot 2023-08-16 at 15 37 30](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/f6107360-2b3c-46ab-b460-3ac25f69d4bd)

Execution:
![Screenshot 2023-08-16 at 15 36 33](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/62d14933-f241-4185-842d-41d65cd794f1)
![Screenshot 2023-08-16 at 15 36 14](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/7e05f9c1-2ccb-4c0d-be8e-3ecf94d858e9)

Result:
![Screenshot 2023-08-16 at 15 36 46](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/7a2df48d-bac7-4528-8f4e-45793a67d05f)

THEN I really went for exact replication, and changed the playbook so state was `absent` again, and it still worked.

Execution:
![Screenshot 2023-08-16 at 15 40 23](https://github.com/PaloAltoNetworks/pan-os-ansible/assets/6574404/3eff653b-0d84-4b70-b758-b5b3b26fef2c)

**Comment by benjamin-rousseau-shift** [comment] 2023-08-18 06:06
Yeah I have the same issue as OP.

So it in UI it shows the push to the device group as succeed, but it contains 0 devices in it (despite having devices in child's device group)

let's say for example : 

- shared
  - headquarters (contain no devices)
    - paris (contains devices)
    
    
 In this scenario if you push to headquarters, it will show success immediatly, but it won't push to any devices, the list of devices will be empty.

**Comment by richardjohnallsopp** [comment] 2023-08-18 06:46
@jamesholland-uk can you suggest what we can do here as we have several people replicating this issue now.

**Comment by jamesholland-uk** [comment] 2023-08-21 09:39
@benjamin-rousseau-shift Yes, I can replicate this with both the Ansible module, but also the XML API, so this is the underlying API working as intended. In comparison FWIW, the GUI (if you debug it via panorama/debug), when you select a parent device group, actually initiates a `commit all` (AKA push) with the **child device group** as an input parameter; the GUI helps you there by calculating the child Device Group to use. Today, if you want to use the Ansible module, or XML API or the Python SDK, you would need to use the Device Group the firewall is directly associated with, not a parent Device Group, and enumerate/calculate the name of this Device Group or have it coded in somewhere or retrievable from a source of truth.

**Comment by benjamin-rousseau-shift** [comment] 2023-08-21 09:42
Hmm is this really intended ? That sounds weird though.
Why would I not be able to push to a parent device group so it applies all changes underneath it ? 

In any case, I managed to workaround that by doing some black magic in my ansible module, but if it's really intended, then maybe it could be part of a feature request I guess ?

**Comment by jamesholland-uk** [comment] 2023-08-21 09:42
For everyone else, do you have the same scenario; is the `panos_commit_push` targeting a parent device group that does not have device directly associated? In which case this conundrum is solved.

If not, more digging required :)

**Comment by jamesholland-uk** [comment] 2023-08-21 09:54
Hi @benjamin-rousseau-shift,
> Hmm is this really intended ? That sounds weird though.
> Why would I not be able to push to a parent device group so it applies all changes underneath it ?
That's how it works today in the XML API per design, yes, it is not a bug. It may not be desirable for all use cases though, I do understand that.

> In any case, I managed to workaround that by doing some black magic in my ansible module, but if it's really intended, then maybe it could be part of a feature request I guess ?
There's two parts to this. First, for the XML API to change, such that "pushing"/`commit-all` to a parent Device Group would execute on firewalls in child Deice Groups, it would require a change in PAN-OS itself. A Feature Request like this can be requested via your usual contacts into Palo Alto Networks. If that was implemented, no changes are required in the PAN-OS Collection for the `panos_commit_push` module.
Second, it could be feasible to have the `panos_commit_push` module "understand" this scenario and try to "push"/`commit-all` to child Device Groups in scenarios where the Device Group in the module parameter does not have any firewalls directly associated. A Feature Request like this can be requested in the Issues in this repo.
In the case of either FR, it would need scoping and feasibility checking, etc (how many child Device Groups down the hierarchy does the process look for firewalls, just one, or all the way, what if devices are associated but disconnected, etc etc). Also, changes in a feature request like this could be deemed breaking changes (some users have Ansible playbooks which work because they assume the Device Group traversal process would not happen) and thus require a major version increment to the Collection, which is something else to consider.
Hope that helps understand the situation.

**Comment by cdot65** [comment] 2023-09-03 17:32
@jamesholland-uk and @richardjohnallsopp 

Once I was able to produce this issue, provided playbook code and screenshots to prove it. However recently I have been unsuccessful in recreating this issue on demand. Some things have changed in my environment but I wanted to point out that I mentioned that the 

> "Object is never pushed to remote firewalls in Device Group."

This was very likely because I had my playbook task set to "absent" 🤦

**Comment by jamesholland-uk** [comment] 2023-09-03 17:41
Thanks @cdot65, much appreciated for the update

**Comment by jamesholland-uk** [comment] 2023-09-03 17:42
For everyone else, do you have the same scenario; is the `panos_commit_push` targeting a parent Device Group that does not have devices directly associated? Only devices in child Device Groups? In which case this conundrum is solved.

Thanks

**Comment by richardjohnallsopp** [comment] 2023-09-03 18:43
This is super frustrating as it’s blocking us moving management of these devices to our Ops team. Given that there is others in this issue which have the same issue what do you suggest we do. I noticed you’re using VM’s have you tried this with physical hardware? Richard AllsoppEpic GamesPrinciple Network Engineer Mobile +447590263111On 3 Sep 2023, at 18:32, Calvin Remsburg ***@***.***> wrote:﻿
@jamesholland-uk and @richardjohnallsopp
Once I was able to produce this issue, provided playbook code and screenshots to prove it. However recently I have been unsuccessful in recreating this issue on demand. Some things have changed in my environment but I wanted to point out that I mentioned that the

"Object is never pushed to remote firewalls in Device Group."

This was very likely because I had my playbook task set to "absent" 🤦

**Comment by jamesholland-uk** [comment] 2023-09-04 11:58
@richardjohnallsopp And your teams' scenario is pushing to a Device Group which has devices directly within it?

**Comment by richardjohnallsopp** [comment] 2023-09-04 12:02
Yeah bud it has all of our global clusters in it. We also set up lab groups and these don’t work either. Richard AllsoppEpic GamesPrinciple Network Engineer Mobile +447590263111On 4 Sep 2023, at 12:58, James Holland ***@***.***> wrote:﻿
@richardjohnallsopp And your teams' scenario is pushing to a Device Group which has devices directly within it?

**Comment by richardjohnallsopp** [comment] 2023-09-04 14:07
Thanks for the info, I’ll get right on this and update the thread. Richard AllsoppEpic GamesPrinciple Network Engineer Mobile +447590263111On 4 Sep 2023, at 14:04, James Holland ***@***.***> wrote:﻿
Ok thanks.
The only way to reliably reproduce this behaviour (so far) is when firewalls are in a child Device Group.
For example, when the playbook has the panos_commit_push task's name parameter set (in this example) to headquarters:
This works:

This does an "empty" push that effectively does nothing:

The compare and contrast of the debug logs, the success followed by the failure, where you can see the success includes the line about the serial number of the device and the failure does not, because there are no firewalls directly associated with the headquarters group:
 tail lines 1000 mp-log logd.log
2023-09-04 13:27:35.216 +0100  ### [CommitAll job enqueued for headquarters. Enqueue time=2023/09/04 13:27:35. JobId=545. User: admin], dgid 0, tplid 0
2023-09-04 13:27:35.217 +0100  ### [CommitAll job started processing. Dequeue time=2023/09/04 13:27:35. JobId=545.User: admin . Commit Description: This is a test.], dgid 21, tplid 0
2023-09-04 13:27:35.324 +0100  ### [Panorama push device-group headquarters for device 77685E5ECFBA with    no flags set.JobId=545.User=admin. Dequeue time=2023/09/04 13:27:35.], dgid 0, tplid 0
2023-09-04 13:27:35.324 +0100  ### [CommitAll job succeeded. Completion time=2023/09/04 13:27:35. JobId=545. User:admin], dgid 21, tplid 0

===========================================================================================================================================================================

2023-09-04 13:33:52.871 +0100  ### [CommitAll job enqueued for headquarters. Enqueue time=2023/09/04 13:33:52. JobId=552. User: admin], dgid 0, tplid 0
2023-09-04 13:33:52.872 +0100  ### [CommitAll job started processing. Dequeue time=2023/09/04 13:33:52. JobId=552.User: admin . Commit Description: This is a test.], dgid 21, tplid 0
2023-09-04 13:33:52.872 +0100  ### [CommitAll job succeeded. Completion time=2023/09/04 13:33:52. JobId=552. User:admin], dgid 21, tplid 0

The compare and contrast of some other debug logs, the success followed by the failure, where you can see the success again starts talking about pushing to the serial number in question, but the failure has nothing about that and the logs just stop, because there are no firewalls directly associated with the headquarters group:
 tail lines 1000 mp-log configd.log
2023-09-04 13:27:35.215 +0100 Commit All job 545 scheduled
2023-09-04 13:27:35.217 +0100 Device 77685E5ECFBA is either single-vsys or multi-vsys and running a pre 10.2 version, push file used is panorama-config.xml
2023-09-04 13:27:35.323 +0100 decrypt sp before pushing
2023-09-04 13:27:35.324 +0100 Panorama push device-group headquarters for device 77685E5ECFBA with    no flags set.JobId=545.User=admin. Dequeue time=2023/09/04 13:27:35.
2023-09-04 13:27:35.325 +0100 Updated job estimate avg time to 0 secs for job type 41

===========================================================================================================================================================================

2023-09-04 13:33:52.870 +0100 Commit All job 552 scheduled

@richardjohnallsopp Whilst I know you described that your Device Group hierarchy has firewalls directly inside the Device Group stated in the name parameter of the panos_commit_push task, maybe you could do some of the debug log commands above and compare contrast the output to the above output from my debug logs. It may give some clues. If you want to share the output on here and it is safe/sanitised, even better. I understand that there is a potential difference of hardware vs software firewalls, but this appears to be primarily a Panorama-focused issue from what I can see. In your scenario, Panorama doesn't seem to even attempt the push (AKA  commit all) to the firewalls.

**Comment by richardjohnallsopp** [comment] 2023-09-27 08:20
@jamesholland-uk so we've had success by basing firewalls inside a parent group. We moved a couple of virtual appliances to a parent group which worked, then we also added them to a child group and that worked as well. So ultimately appliances have to be based in a parent group.

**Comment by jamesholland-uk** [comment] 2023-09-27 08:41
Thanks @richardjohnallsopp. Are we ok to close this one?

**Comment by richardjohnallsopp** [comment] 2023-09-27 08:55
Yeah I think so

**Closed** 2023-09-27 08:58 UTC
Labels: bug
