### ISSUE TITLE
Import cert with panos_import

### ISSUE THREAD

**Issue by ai-ryanbess** [PaloAltoNetworks/pan-os-ansible#412] opened 2023-04-04 15:08 UTC
attempting to import a cert into panorama.  WIth the below 
  tasks:  
    - name: upload cert to panorama
      # https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_import_module.html
      paloaltonetworks.panos.panos_import:
        provider: '{{ device }}'
        template_stack: 'somestack'
        category: 'keypair'
        certificate_name: 'test12345678a'
        format: 'pkcs12'
        filename: 'cert.pfx'
        passphrase: "{{  passphrase }}"
      delegate_to: localhost

it results in fatal: [localhost]: FAILED! => {"changed": false, "msg": "<response status = 'error' code = '400'><result><msg>Request is not a valid XML</msg></result></response>"}

**Comment by jamesholland-uk** [comment] 2023-04-05 10:46
Hi @ai-ryanbess, I am unable to replicate this one. It currently works for me with:
```
python 3.10.4
pan-os-python 1.8.1
pan-python 0.17.0
paloaltonetworks.panos 2.13.2
pan-os 11.0.1
````
<img width="1140" alt="Screenshot 2023-04-05 at 11 41 10" src="https://user-images.githubusercontent.com/6574404/230058096-965edbc4-e26b-443d-8b80-4dbd578f39ee.png">
<img width="809" alt="Screenshot 2023-04-05 at 11 43 29" src="https://user-images.githubusercontent.com/6574404/230058340-fe428968-c9cb-433f-b29d-dd0126c9a6dd.png">

Can you share more details of your environment, and maybe run ansible with verbose mode etc to look for clues to the failure? Thanks

**Comment by ai-ryanbess** [comment] 2023-04-05 11:26
Hey James,
Here you go.  This is the first time we're attempting to do this so not like it used to work.

Python 3.9.13
pan-os-python 1.8.1
pan-python 0.17.0
paloaltonetworks.panos 
pan-os 10.2.2-h2



TASK [upload cert to panorama] ********************************************************************************************************************************************************************
task path: /home/username/ansible_sni_windows/local/cert.yaml:16
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: username
<127.0.0.1> EXEC /bin/sh -c 'echo ~username && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp `"&& mkdir "` echo /home/username/.ansible/tmp/ansible-tmp-1680693024.8957407-451105-194972674477174 `" && echo ansible-tmp-1680693024.8957407-451105-194972674477174="` echo /home/username/.ansible/tmp/ansible-tmp-1680693024.8957407-451105-194972674477174 `" ) && sleep 0'
Including module_utils file ansible/__init__.py
Including module_utils file ansible/module_utils/__init__.py
Including module_utils file ansible/module_utils/basic.py
Including module_utils file ansible/module_utils/_text.py
Including module_utils file ansible/module_utils/common/_collections_compat.py
Including module_utils file ansible/module_utils/common/__init__.py
Including module_utils file ansible/module_utils/common/_json_compat.py
Including module_utils file ansible/module_utils/common/_utils.py
Including module_utils file ansible/module_utils/common/arg_spec.py
Including module_utils file ansible/module_utils/common/file.py
Including module_utils file ansible/module_utils/common/locale.py
Including module_utils file ansible/module_utils/common/parameters.py
Including module_utils file ansible/module_utils/common/collections.py
Including module_utils file ansible/module_utils/common/process.py
Including module_utils file ansible/module_utils/common/sys_info.py
Including module_utils file ansible/module_utils/common/text/converters.py
Including module_utils file ansible/module_utils/common/text/__init__.py
Including module_utils file ansible/module_utils/common/text/formatters.py
Including module_utils file ansible/module_utils/common/validation.py
Including module_utils file ansible/module_utils/common/warnings.py
Including module_utils file ansible/module_utils/compat/selectors.py
Including module_utils file ansible/module_utils/compat/__init__.py
Including module_utils file ansible/module_utils/compat/_selectors2.py
Including module_utils file ansible/module_utils/compat/selinux.py
Including module_utils file ansible/module_utils/distro/__init__.py
Including module_utils file ansible/module_utils/distro/_distro.py
Including module_utils file ansible/module_utils/errors.py
Including module_utils file ansible/module_utils/parsing/convert_bool.py
Including module_utils file ansible/module_utils/parsing/__init__.py
Including module_utils file ansible/module_utils/pycompat24.py
Including module_utils file ansible/module_utils/six/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py
Including module_utils file ansible/module_utils/connection.py
Including module_utils file ansible/module_utils/common/json.py
Including module_utils file ansible_collections/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/panos/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/panos/plugins/__init__.py
Including module_utils file ansible_collections/paloaltonetworks/panos/plugins/module_utils/__init__.py
Using module file /home/username/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py
<127.0.0.1> PUT /home/username/.ansible/tmp/ansible-local-4511012quajk0v/tmprf4q16h0 TO /home/username/.ansible/tmp/ansible-tmp-1680693024.8957407-451105-194972674477174/AnsiballZ_panos_import.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/username/.ansible/tmp/ansible-tmp-1680693024.8957407-451105-194972674477174/ /home/username/.ansible/tmp/ansible-tmp-1680693024.8957407-451105-194972674477174/AnsiballZ_panos_import.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/username/.ansible/tmp/ansible-tmp-1680693024.8957407-451105-194972674477174/AnsiballZ_panos_import.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/username/.ansible/tmp/ansible-tmp-1680693024.8957407-451105-194972674477174/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "category": "keypair",
            "certificate_name": "test12345678a",
            "custom_logo_location": null,
            "filename": "cert.pfx",
            "format": "pkcs12",
            "ip_address": null,
            "passphrase": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "password": null,
            "port": 443,
            "profile_name": null,
            "provider": {
                "api_key": null,
                "ip_address": "panorama.domain.com",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 443,
                "serial_number": null,
                "username": "ServiceAccount"
            },
            "template": null,
            "template_stack": "TemplateStack",
            "url": null,
            "username": "admin"
        }
    },
    "msg": "<response status = 'error' code = '400'><result><msg>Request is not a valid XML</msg></result></response>"

**Comment by ai-ryanbess** [comment] 2023-04-05 11:53
Just tried a different cert and it worked just fine.  With that said, the cert i'm unable to upload via the api uploads just fine via the panorama web.

**Comment by jamesholland-uk** [comment] 2023-04-05 11:55
Hard one to diagnose without the certs. Is the cert formatted to the usual standard? No extra metadata or anything, which the API could reject but a web browser would interpret differently as it passes into the web GUI?

**Comment by ai-ryanbess** [comment] 2023-04-05 12:06
everything looks correct about the cert.  It uploads to pan via the web just fine.  It imports to windows servers cert store just fine.  It can be used in IIS just fine.  Any commands i can run against the cert or pull logs from the API that may shed some light?

**Comment by jamesholland-uk** [comment] 2023-04-05 12:26
You could try `tail follow yes mp-log configd.log`, in there I see a log entry `writing RSA key` whilst executing the playbook.

Maybe try importing working and non-working certs with the XML API as well, Postman or script or whatever works? For example in Postman:
`https://{{host}}/api/?key={{key}}&type=import&category=keypair&format=pkcs12&certificate-name={{cert-name}}&target-tpl={{template-name}}&passphrase=redacted`
<img width="1087" alt="Screenshot 2023-04-05 at 13 25 11" src="https://user-images.githubusercontent.com/6574404/230079772-9e082ad8-41ab-49f3-ae7e-d2466ba27791.png">

**Comment by ai-ryanbess** [comment] 2023-04-05 12:36
Figured it out.  The passphrase contains an '&'.  This blows the entire thing up.  Can you please retest in your lab?

**Comment by jamesholland-uk** [comment] 2023-04-05 12:39
Yes, adding a `&` to the passphrase generates the same error on my side as per your original post

**Comment by jamesholland-uk** [comment] 2023-04-05 12:47
Looks like `&` is an RFC-defined reserved sub-delim ([ref](https://www.rfc-editor.org/rfc/rfc3986#section-2.2)) so I think this is expected behaviour. You could try replacing the `&` with `%26` though?

**Comment by ai-ryanbess** [comment] 2023-04-05 13:51
i'm not sure i understand what you are trying to say.  There's no RFC that i'm aware of that says for a cert passphrase you can not use an '&' as a part of that passphrase.  It's also my understanding that the api and the GUI are to behave similar.  Is the issue that these modules use the XML api and NOT the rest api?

**Comment by ai-ryanbess** [comment] 2023-04-05 14:24
So those that are listed in the sub-delim section (2.2 below) all need to be corrected for?

https://www.rfc-editor.org/rfc/rfc3986#section-2.2

**Comment by jamesholland-uk** [comment] 2023-04-05 14:42
I have not tested them all, I think `&` is probably the worst one because of how URL parameters work with that character, but others could be blockers too and need encoding

**Comment by ai-ryanbess** [comment] 2023-04-05 17:11
I just tested by storing the passphrase with the & in it, then doing a replace ('&', '%26').  This failed.  Thoughts?

**Comment by ai-ryanbess** [comment] 2023-04-05 18:10
so you can pass the urlencode filter so no matter what is in the passphrase, it should be in the appropriate format.  THe problem now as i see it is the modules dont' know that string is encoded and is literally reading it as a string.  How can we get around this?

**Comment by jamesholland-uk** [comment] 2023-04-06 08:20
> I just tested by storing the passphrase with the & in it, then doing a replace ('&', '%26'). This failed. Thoughts?

I only tested with a %26 in a hardcoded string, and that worked. The mechanism for doing the string amendment is more an Ansible question than a PAN-OS question, but this worked for me: `passphrase: "{{ passphrase | urlencode() }}"`

> THe problem now as i see it is the modules dont' know that string is encoded and is literally reading it as a string. How can we get around this?

I'm not sure I understand this one, can you provide any more details? Thank you

**Comment by RyanMBess** [comment] 2023-04-06 11:34
I can not preproduce that running against 10.2.h2.  Lets say the passphrase is abcdefg&123.  You are saying that you hard coded your passphrase to be abcdefg%26123

so like in the vars section
vars:
     passphrase: abcdefg%26123

then in the play to upload the cert it looked like this and it worked for you?

    - name: upload cert to panorama
      # https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_import_module.html
      paloaltonetworks.panos.panos_import:
        provider: '{{ device }}'
        template_stack: 'somestack' 
        category: 'keypair'
        certificate_name: 'test'
        format: 'pkcs12'
        filename: '/tmp/cert.pfx'
        passphrase: '{{  passphrase | urlencode()  }}'

**Comment by jamesholland-uk** [comment] 2023-04-06 11:47
Yes, I tested successfully with a string including a `%26`, but then also tested with a string including a `&` which I thought was more relevant (because in a lot of scenarios the passphrase will most likely be sent into this playbook as a variable from a secrets management system so will not be preprocessed to remove or encode special characters). I therefore used the urlencode function per the previous comment; here's what worked: https://github.com/jamesholland-uk/playground/blob/main/pan-os-ansible/certificate_tasks.yml

**Comment by jamesholland-uk** [comment] 2023-04-06 12:33
My apologies, my testing this morning was indeed flawed, I now get the same results as you. Sorry for the unexpected diversion.
Given the passphrase is part of a query string sent to the XML API under the hood of these modules, and encoding is the only feasible solution to pass the passphrase into any web server, the receiving server (in this case PAN-OS) would need to do the decoding. This would need a PAN-OS change, something you would need to raise with your account team and also a TAC ticket as a reference. Once the XML API has a way to pass in a passphrase containing special characters like `&` (presumably with PAN-OS being enhanced to decode special characters, but there could be other ways) we can work with that solution in these Ansible modules; there may or may note be any changes needed in the modules, it depends on the solution released. Meanwhile, the short-term solution I think would be to avoid using `&` in the passphrase.

**Comment by jamesholland-uk** [comment] 2023-04-06 13:52
On the latter query, I've [opened an FR](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/415) to track this for you

**Comment by jamesholland-uk** [comment] 2023-07-04 09:14
Hi @RyanMBess, the `block export of private key` feature was released. I will close this issue now, as it is not something we can fix with Ansible, it needs a PAN-OS change. If any new or different information comes to light, we can reopen this issue if required.

**Closed by jamesholland-uk** 2023-07-04 09:14 UTC
Labels: bug
