### ISSUE TITLE
HA module does not work for NGFW-VM on AWS

### ISSUE THREAD

**Issue by Joe-Zhou-Pub** [PaloAltoNetworks/pan-os-ansible#235] opened 2021-06-17 23:41 UTC
## Describe the bug

The ansible HA module can not configure NGFW-VM HA with error of index out of range

## Expected behavior

Please the NGFW-VM HA configure document https://docs.paloaltonetworks.com/vm-series/10-0/vm-series-deployment/set-up-the-vm-series-firewall-on-aws/high-availability-for-vm-series-firewall-on-aws/configure-activepassive-ha-on-aws.html

It has to use the management port as the HA1 port. Can not be hardware firewall like ethernet1/x.

## Current behavior

The panos_ha always expect the HA port is ethernet1/x

## Steps to reproduce

Please see the playbook:

---
- hosts: localhost
connection: local
gather_facts: no

collections:
- paloaltonetworks.panos

 

tasks:
- name: Include variables
include_vars: provider.yml
no_log: yes

- name: Set primary HA port
panos_interface:
provider: '{{ primary }}'
state: present
if_name: '{{ item }}'
mode: "ha"
enable_dhcp: false
with_items:
- ethernet1/1

- name: Config primary control links
panos_ha:
provider: '{{ primary }}'
state: present
ha_peer_ip: "10.2.240.252"
ha1_ip_address: "10.2.240.236"
ha1_netmask: "255.255.255.0"
ha1_port: "ethernet0/0"
ha2_port: "ethernet1/1"

## Screenshots

(.venv) 14:26 % ansible-playbook -i 127.0.0.1, -e "ansible_python_interpreter=$(which python)" vm-ha.yml 

PLAY [localhost] ***************************************************************************************************************************************************************************************************************************

TASK [Include variables] *******************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Set primary HA port] *****************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => (item=ethernet1/1)

TASK [Config primary control links] ********************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n File \"/Users/jozhou/.ansible/tmp/ansible-tmp-1623619631.2409449-82377-159027178184794/AnsiballZ_panos_ha.py\", line 100, in <module>\n _ansiballz_main()\n File \"/Users/jozhou/.ansible/tmp/ansible-tmp-1623619631.2409449-82377-159027178184794/AnsiballZ_panos_ha.py\", line 92, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File \"/Users/jozhou/.ansible/tmp/ansible-tmp-1623619631.2409449-82377-159027178184794/AnsiballZ_panos_ha.py\", line 40, in invoke_module\n runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_ha', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_ha', _modlib_path=modlib_path),\n File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n return _run_module_code(code, init_globals, run_name, mod_spec)\n File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n _run_code(code, mod_globals, init_globals,\n File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n exec(code, run_globals)\n File \"/var/folders/qy/dvxp9_ps17z3k5_nmy95vt6mzsqgps/T/ansible_panos_ha_payload_zsopcaxw/ansible_panos_ha_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_ha.py\", line 452, in <module>\n File \"/var/folders/qy/dvxp9_ps17z3k5_nmy95vt6mzsqgps/T/ansible_panos_ha_payload_zsopcaxw/ansible_panos_ha_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_ha.py\", line 439, in main\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
127.0.0.1 : ok=2 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0

## Your Environment

NGFW-Vm on AWS version 10.0.6

- Collection: 2.6.0
- Python: 3.9.5
- Ansible: 4.1.0
- PAN-OS Python Library & version (e.g. pandevice 0.14.0, pan-os-python 1.0.2): pan-python: 0.16.0 pan-os-python: 1.2.0

**Comment by ntwrkguru** [comment] 2021-08-31 12:28
Duplicate of #32

**Comment by jamesholland-uk** [comment] 2023-02-08 13:04
This issue was fixed in [2.8.0](https://github.com/PaloAltoNetworks/pan-os-ansible/releases/tag/v2.8.0). Please reopen if there is still an issue using a version of the collection 2.8.0 or above.

**Closed by jamesholland-uk** 2023-02-08 13:04 UTC
Labels: bug
